name: CI

on:
  push:
    branches:
    - 'dev'

permissions:
  contents: read

env:
  NFPM_VERSION: 'v2.35.3'
  GOPROXY: "direct"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
            go-version-file: 'go.mod'
            cache: false
      - name: Lint
        run:
          |
          make lint

  unit-test:
      name: Unit Tests
      runs-on: ubuntu-22.04
      permissions:
        contents: write
      steps:
          - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
          - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
            with:
                go-version-file: 'go.mod'
                cache: false
          - name: Run Unit Tests
            run: make unit-test

  race-condition-test:
      name: Unit tests with race condition detection
      runs-on: ubuntu-22.04
      steps:
          - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
          - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
            with:
                go-version-file: 'go.mod'
                cache: false
          - name: Run unit tests with race condition detection
            run: make race-condition-test

  build-unsigned-snapshot:
      name: Build Unsigned Snapshot
      runs-on: ubuntu-22.04
      steps:
          - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
            with:
              fetch-tags: 'true'
          - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
            with:
                go-version-file: 'go.mod'
                cache: false
          - name: Setup Build Environment
            run: go install github.com/goreleaser/nfpm/v2/cmd/nfpm@${{ env.NFPM_VERSION }}
          - name: Build Packages
            run: |
                make clean local-deb-package local-rpm-package local-apk-package
